name: OmicronPE-ShopUI
main: GuiShop\Main
version: 2
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: NicKPlayzz
description: ShopUI for servers!
commands:
 shop:
  description: Access The ShopUI
